# Generated by Django 4.1.5 on 2023-01-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='staff',
        ),
    ]
