# Generated by Django 4.1.5 on 2023-02-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing and Apparel', 'Clothing and Apparel'), ('Home and Kitchen Appliances', 'Home and Kitchen Appliances'), ('Beauty and Personal Care Products', 'Beauty and Personal Care Products'), ('Food', 'Food'), ('Sporting Goods and Fitness Equipment', 'Sporting Goods and Fitness Equipment'), ('Automotive Parts and Accessories', 'Automotive Parts and Accessories'), ('Medical and Healthcare Supplies', 'Medical and Healthcare Supplies'), ('Office Supplies and Equipment', 'Office Supplies and Equipment'), ('Industrial and Construction Materials', 'Industrial and Construction Materials')], max_length=50, null=True),
        ),
    ]
